### ISSUE TITLE
Are you in need of 3D models?

### ISSUE THREAD

**Issue by michaelizer** [mayank-agg/3d-tictactoe#1]
Greetings, 

I have experience modeling in 3D, just wanted to know if you want me to do some 3D models for your tic-tac-toe game. I come from Utopian.io which rewards contributions to open source projects like yours, just let me know what do you think?

**Comment by mayank-agg** [comment]
Hey this is a 3rd year level computing assignment. So we are not allowed to accept any contributions. Thanks though. I'll keep in touch for future projects.

**Comment by michaelizer** [comment]
Well, that sounds difficult. Could you share a picture of any models you
Made? Just to check my skill :)

**Comment by mayank-agg** [comment]
We have not made any models, yet. Sorry!
